//! Wires the tauri-specta `Builder` and (in debug builds, or when the binary
//! is launched with `--export-bindings`) writes `src/lib/bindings.ts`.

use std::path::PathBuf;
use tauri::Wry;
use tauri_specta::{collect_commands, collect_events, Builder};

/// Builds the `tauri-specta` Builder with every Specdex command + event
/// registered. Plan 20 extends `commands!` / `events!` to cover the full
/// surface; plan 04 ships only `get_app_version`.
///
/// Commands are referenced by full path so the helper macros that
/// `#[tauri::command]` / `#[specta::specta]` generate resolve correctly from
/// this module.
pub fn builder() -> Builder<Wry> {
    Builder::<Wry>::new()
        .commands(collect_commands![crate::commands::app::get_app_version])
        .events(collect_events![])
}

/// Returns the on-disk path that bindings should be written to.
///
/// Anchored to `CARGO_MANIFEST_DIR` so it works regardless of where Cargo
/// was invoked. `crates/tauri_adapter` -> `crates` -> `src-tauri` -> repo
/// root -> `src/lib/bindings.ts`.
pub fn bindings_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("..")
        .join("src")
        .join("lib")
        .join("bindings.ts")
}

/// Exports bindings to disk. Idempotent — overwrites existing file.
/// Errors are returned so callers can decide whether to abort or warn.
pub fn export() -> Result<(), Box<dyn std::error::Error>> {
    // `@ts-nocheck`: the generated globals block emits helpers (TAURI_CHANNEL,
    // __makeEvents__) that are unused with a minimal command surface, which
    // `noUnusedLocals` rejects. Exported types stay fully usable by importers.
    let cfg = specta_typescript::Typescript::default()
        .header("// @ts-nocheck\n// AUTO-GENERATED by tauri-specta. Do not edit. Run `pnpm bindings` to regenerate.\n")
        .bigint(specta_typescript::BigIntExportBehavior::Number);
    let path = bindings_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    builder().export(cfg, &path)?;
    tracing::info!(?path, "exported tauri-specta bindings");
    Ok(())
}
