//! Wires the tauri-specta `Builder` and (in debug builds, or when the binary
//! is launched with `--export-bindings`) writes `src/lib/bindings.ts`.

use std::path::PathBuf;
use tauri::Wry;
use tauri_specta::{collect_commands, collect_events, Builder};

/// Builds the `tauri-specta` Builder with every Specdex command registered.
/// Events flow through the single `specdex://event` channel (see
/// `event_forwarder`), so `collect_events!` stays empty.
///
/// Commands are referenced by full path so the helper types that
/// `#[tauri::command]` / `#[specta::specta]` generate resolve correctly from
/// this module.
pub fn builder() -> Builder<Wry> {
    use crate::commands::{
        app, backup, entry, identity, ingest, kb, scanner, search, settings, source_doc,
    };
    Builder::<Wry>::new()
        .commands(collect_commands![
            app::get_app_version,
            settings::get_app_settings,
            settings::reveal_in_file_manager,
            identity::identity_get,
            identity::identity_set,
            kb::kb_create,
            kb::kb_get,
            kb::kb_list,
            kb::kb_list_summaries,
            kb::kb_update_meta,
            kb::kb_delete,
            kb::kb_migrate_schema,
            entry::entry_create,
            entry::entry_get,
            entry::entry_list,
            entry::entry_update,
            entry::entry_delete,
            entry::entry_bulk_delete,
            ingest::ingest_files,
            source_doc::source_doc_get,
            ingest::source_doc_list_recent,
            source_doc::source_doc_delete,
            source_doc::source_doc_resolve_path,
            source_doc::find_in_document,
            scanner::scan_document,
            scanner::scanner_invalidate,
            search::search_entries,
            search::search_source_docs,
            backup::backup_export,
            backup::backup_restore,
            backup::kb_export_json,
            backup::kb_import_json,
        ])
        .events(collect_events![])
}

/// Returns the on-disk path that bindings should be written to.
///
/// Anchored to `CARGO_MANIFEST_DIR` (the adapter crate at `<repo>/src-tauri`),
/// so one `..` reaches the repo root -> `src/lib/bindings.ts`.
pub fn bindings_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("src")
        .join("lib")
        .join("bindings.ts")
}

/// Exports bindings to disk. Idempotent — overwrites existing file.
/// Errors are returned so callers can decide whether to abort or warn.
pub fn export() -> Result<(), Box<dyn std::error::Error>> {
    // `@ts-nocheck`: the generated globals block emits helpers (TAURI_CHANNEL,
    // __makeEvents__) that are unused with a minimal command surface, which
    // `noUnusedLocals` rejects. Exported types stay fully usable by importers.
    let cfg = specta_typescript::Typescript::default()
        .header("// @ts-nocheck\n// AUTO-GENERATED by tauri-specta. Do not edit. Run `pnpm bindings` to regenerate.\n")
        .bigint(specta_typescript::BigIntExportBehavior::Number);
    let path = bindings_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    builder().export(cfg, &path)?;
    tracing::info!(?path, "exported tauri-specta bindings");
    Ok(())
}
